# Final Validation of the selected model

Here the final validation and visualization of the selected model is performed.

### Importing the standard libraries

In [11]:
import numpy as np
import pandas as pd
%matplotlib inline
import matplotlib.pyplot as plt

### Importing the dataset

In [12]:
dataset = pd.read_csv('../assets/car-details-for-ml-fuel-types.csv')

dataset.head()

km_driven  seats  mileage  engine  max_power      nm  selling_price  fuel
0     145500    5.0    23.40    1248      74.00  190.00         450000     0
1     120000    5.0    21.14    1498     103.52  250.00         370000     0
2     140000    5.0    17.70    1497      78.00  124.54         158000     1
3     127000    5.0    23.00    1396      90.00  219.67         225000     0
4     120000    5.0    16.10    1298      88.20  112.78         130000     1

### Splitting the dataset into the Training and Test set

In [13]:
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=73)

### Feature scaling the data

The artificial neural network requires feature scaled data.

In [15]:
from sklearn.preprocessing import StandardScaler

std_scaler = StandardScaler()

X_train_scaled = std_scaler.fit_transform(X_train)
X_test_scaled = std_scaler.transform(X_test)

# Sample the scaled values
print(X_train_scaled[:1, :12])
print(X_test_scaled[:1, :12])

[[-0.23 -0.45  0.59 -0.9  -0.7  -0.98 -0.64]]
[[-1.02 -0.45 -0.38  1.05  3.04  2.62  5.11]]


## Artificial Neural Network Classification

Let's import the model from the model selection notebook, since it is the model we will use for the final validation.

In [16]:
from tensorflow.python.keras.api import keras

ann_class = keras.models.load_model('../assets/ann_class.h5')

Let's see if the model is working as expected.

In [17]:
y_pred = ann_class.predict(X_test_scaled)
y_pred = (y_pred > 0.5)

np.set_printoptions(precision=2)
actual_vs_pred = np.concatenate((y_test.reshape(len(y_test), 1), y_pred.reshape(len(y_pred), 1)), 1)

print(["Actual", "Predictions"])
print(actual_vs_pred[4:12])

['Actual', 'Predictions']
[[0 0]
 [0 0]
 [1 1]
 [1 1]
 [0 0]
 [1 1]
 [1 1]
 [0 0]]


In [18]:
from sklearn.metrics import confusion_matrix, accuracy_score

accuracy = accuracy_score(y_test, y_pred)
cm = confusion_matrix(y_test, y_pred)

print("Accuracy: ", accuracy)
print("Confusion Matrix: \n", cm)

Accuracy:  1.0
Confusion Matrix: 
 [[866   0]
 [  0 668]]


Perfect. The model still performs like it should. Time to do some visualization and see if the model can predict some real world data to perfection.

## Visualizing the results